'use client';

import { useEffect } from 'react';
import type { Dispatch, MutableRefObject, SetStateAction } from 'react';
import type { Mode, Player, TournamentState } from '../lib/types';

interface Params {
  remote: TournamentState | undefined;
  mode: Mode;
  playersRef: MutableRefObject<Player[]>;
  drawingRef: MutableRefObject<boolean>;
  setMode: Dispatch<SetStateAction<Mode>>;
  setUndoStack: Dispatch<SetStateAction<string[]>>;
  generateDraw: () => void;
}

/** Starts a draw when the page is opened with ?generateDraw=singles|doubles. */
export function useAutoGenerateDraw({
  remote,
  mode,
  playersRef,
  drawingRef,
  setMode,
  setUndoStack,
  generateDraw,
}: Params) {
  useEffect(() => {
    if (typeof window === 'undefined' || !remote) return;
    const pending = new URLSearchParams(window.location.search).get('generateDraw');
    if (pending !== 'singles' && pending !== 'doubles') return;
    if (pending !== mode) {
      setMode(pending);
      setUndoStack([]);
      return;
    }
    if (drawingRef.current) return;
    const list = remote.playersList ?? [];
    if (list.length < 2) return;
    playersRef.current = list;
    const timeoutId = window.setTimeout(() => generateDraw(), 0);
    return () => window.clearTimeout(timeoutId);
  }, [remote, mode, generateDraw, setMode, setUndoStack, playersRef, drawingRef]);
}
