'use client';

import { useCallback, useEffect, useRef } from 'react';
import type { Dispatch, MutableRefObject, SetStateAction } from 'react';
import { buildInitialBracket } from '../lib/drawInit';
import { uniqueDrawEntries } from '../lib/drawPool';
import type { BracketData, MatchDetails, Mode, Player, TournamentState } from '../lib/types';
import { useAutoGenerateDraw } from './useAutoGenerateDraw';
import { runDrawAnimation } from './runDrawAnimation';

interface Params {
  remote: TournamentState | undefined;
  mode: Mode;
  playersRef: MutableRefObject<Player[]>;
  approvedForMode: Player[];
  drawingRef: MutableRefObject<boolean>;
  setMode: Dispatch<SetStateAction<Mode>>;
  setIsDrawing: Dispatch<SetStateAction<boolean>>;
  setUndoStack: Dispatch<SetStateAction<string[]>>;
  setBracketData: Dispatch<SetStateAction<BracketData>>;
  setMatchDetails: Dispatch<SetStateAction<MatchDetails>>;
  persist: (bd: BracketData, md: MatchDetails, pl: Player[], opts?: { revalidate?: boolean }) => Promise<void>;
  pushHistory: () => void;
}

export function useDrawGeneration({
  remote,
  mode,
  playersRef,
  approvedForMode,
  drawingRef,
  setMode,
  setIsDrawing,
  setUndoStack,
  setBracketData,
  setMatchDetails,
  persist,
  pushHistory,
}: Params) {
  const drawIntervalRef = useRef<ReturnType<typeof setInterval> | null>(null);

  useEffect(() => {
    return () => {
      if (drawIntervalRef.current) clearInterval(drawIntervalRef.current);
    };
  }, []);

  const resetDraw = useCallback(() => {
    pushHistory();
    const currentPlayers = uniqueDrawEntries(approvedForMode, mode);
    const { bracketData, matchDetails } = buildInitialBracket(currentPlayers);
    setBracketData(bracketData);
    setMatchDetails(matchDetails);
    persist(bracketData, matchDetails, currentPlayers);
  }, [mode, approvedForMode, persist, pushHistory, setBracketData, setMatchDetails]);

  const generateDraw = useCallback(() => {
    if (drawingRef.current) return;
    const currentPlayers = uniqueDrawEntries(approvedForMode, mode);
    if (currentPlayers.length < 2) return;

    pushHistory();
    drawingRef.current = true;
    setIsDrawing(true);

    const { bracketData: bd, matchDetails: md, stats: s, slots } =
      buildInitialBracket(currentPlayers);
    setBracketData(bd.map((r) => [...r]));
    setMatchDetails(md.map((r) => [...r]));
    if (drawIntervalRef.current) clearInterval(drawIntervalRef.current);

    drawIntervalRef.current = runDrawAnimation({
      bd,
      md,
      slots,
      size: s.size,
      currentPlayers,
      persist,
      drawingRef,
      drawIntervalRef,
      setIsDrawing,
      setBracketData,
      setMatchDetails,
      writeChain: persist(bd, md, currentPlayers, { revalidate: false }),
    });
  }, [mode, persist, pushHistory, approvedForMode, drawingRef, setIsDrawing, setBracketData, setMatchDetails]);

  useAutoGenerateDraw({
    remote,
    mode,
    playersRef,
    drawingRef,
    setMode,
    setUndoStack,
    generateDraw,
  });

  return { generateDraw, resetDraw };
}
